---
- name: update whole os
  yum:
    name: '*'
    state: latest
    update_cache: yes

- name: add kubernetes repo
  yum_repository:
    name: "{{ k8s_yum_name }}"
    baseurl: "{{ k8s_yum_baseurl }}"
    enabled: "{{ k8s_yum_enabled }}"
    gpgcheck: "{{ k8s_yum_gpgcheck }}"
    repo_gpgcheck: "{{ k8s_yum_repo_gpgcheck }}"
    gpgkey: "{{ k8s_yum_gpgkey }}"
    exclude: "{{ k8s_yum_exclude }}"
    description: "Kubernetes Repo"
    state: present

- name: set selinux to permissive
  selinux:
    state: permissive
    policy: targeted
  
- name: install required packages
  yum:
    name: "{{ item }}"
    update_cache: yes
    state: latest
    disable_excludes: kubernetes
  with_items: 
  - "{{ k8s_required_packages }}"

- name: create docker group
  group:
    name: docker
    state: present

- name: add user vagrant to docker group
  user:
    name: vagrant
    append: yes
    groups: docker

- name: add netfilter module
  modprobe:
    name: br_netfilter
    state: present

- name: remove swapfile from /etc/fstab
  mount:
    name: swap
    fstype: swap
    state: absent

- name: disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: set some kernel parameters
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    reload: yes
    state: present
  with_items:
  - "{{ k8s_required_sysctl_cfg }}"

- name: kubelet extra args
  template:
    src: kubelet.j2
    dest: /etc/default/kubelet

- name: enable and start services
  systemd:
    name: "{{ item }}"
    daemon_reload: yes
    enabled: yes
    state: started
    masked: no
  with_items:
    - kubelet
    - docker